codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
        
      core:
        target: 80%
        threshold: 1%
        paths:
          - "src/core/**/*"
          
      tools:
        target: 60%
        threshold: 2%
        paths:
          - "src/tools/**/*"
          
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto

parsers:
  javascript:
    enable_partials: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/test-utils/**"
  - "**/mocks/**"
  - "tests/**"
  - "coverage/**"
  - "dist/**"
  - "node_modules/**"
  - "**/*.config.js"
  - "scripts/**"

flags:
  unittests:
    paths:
      - "src/**"
    carryforward: true